sudo: false

language: node_js

node_js:
  - '4'
  - '6'
  - stable

# always use npm latest
before_install:
  - npm i -g npm

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8

script:
  - npm run lint
  - npm run coverage

after_success:
  - npm run coverage-publish